### ISSUE TITLE
Drupal 8 Follow Ups

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#391]
- [ ] Get the menu routes working (workaround is building the webroot) https://github.com/kalamuna/kalastatic_dot_module/issues/42
- [x] Make sure permissions are in there https://github.com/kalamuna/kalastatic_dot_module/issues/43
- [x] Share the assets (CSS/JS) from KSTAT to Drupal https://github.com/kalamuna/kalastatic_dot_module/issues/44
- [x] Share the assets (CSS/JS) from Drupal to KSTAT https://github.com/kalamuna/kalastatic_dot_module/issues/44

**Comment by andrewmallis** [comment]
Created an issue in kstat_module to get the permissions and menu routes moving (very slowly)
https://github.com/kalamuna/kalastatic_dot_module/issues/56
