### ISSUE TITLE
Drupal 8 Epic

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#471]
- [ ] https://github.com/kalamuna/kalastatic_dot_module/issues/24 Assets Menu Router
- [ ] https://github.com/kalamuna/kalastatic_dot_module/issues/32 Automatically register twig namespaces (Extend Components)
- [ ] Utility PHP functions for Image Styles/etc
- [ ] https://github.com/kalamuna/kalastatic_dot_module/issues/36 Discover the Kalastatic Configuration
